### ISSUE TITLE
Add custom G-code M900 Kxx to filaments

### ISSUE THREAD

**Issue by 3d-gussner** [prusa3d/Slic3r-settings#18]
Since Prusa firmware 3.0.12-7 the 'Linear Advance Integration' is activated.
Can you please add the custom g-code 'M900 Kxx' to the filaments?
I also think you should check with your firmware team how a printer with older firmware handles the 'unknown' M900 Kxx g-code to prevent issues with customers/prints.

**Comment by ManuGithubSteam** [comment]
I secon this :-) Great Idea!

**Comment by jindrichbenes** [comment]
Custom M900 Gcode added to MK2 filament settings, M900 added also to MM printer settings for now.

**Comment by 3d-gussner** [comment]
@jindrichbenes Why did you put the Linear Advanced M900 K100 value to the printer settings? As the value differs by the used filament it should be used/added there and per know filament!
I don't know in which order the start g-code is written to the g-code file, but if there is a M900 Kxx start g-code defined in the filament settings it should overwrite any other M900 Kyy g-code coming from the printer settings!

**Comment by jindrichbenes** [comment]
M900 K200 was added to **MultiMaterial** 0.4 nozle since the value needs to be quite large and as of now, this value seems to perform well on different materials. We will do specific values for different filaments on MMU if we find out it's necessary.
M900 K100 was added to **MultiMaterial** 0.6 nozzle, larger nozzles seem to need smaller linear advance.

MK2(S) got different K values for different filaments.

MK2(S) and MMU filament settings are separate.

**Comment by 3d-gussner** [comment]
@jindrichbenes Thanks.
Do you know if a filament settings custom g-code overwrites the printer setting g-code in Slic3r?

**Comment by jindrichbenes** [comment]
Yes, but for whole print.
i.e. if you have M900 K100 in printer gcode and M900 K50 in filament gcode, start gcode will have lines

M900 K100
M900 K50

K50 being active for whole print
