### ISSUE TITLE
Missing Prusa EasyABS settings

### ISSUE THREAD

**Issue by coolcow** [prusa3d/Slic3r-settings#20]
EasyABS is labeled with a temperature range of 220-240 deegres.

But the [Prusa ABS settings](https://github.com/prusa3d/Slic3r-settings/blob/master/Slic3r%20settings%20MK2/filament/Prusa%20ABS%201.75mm.ini) are using 255 deegrees. Also, the part cooling fan is turned of with this settings, which results in aweful print quality => 
![img_20170924_202423](https://user-images.githubusercontent.com/2337234/30805029-f13f0d2e-a1ef-11e7-94ba-0f19803e391e.jpg)

When i lower the temperature to 240 deegrees and use the part cooling at 15-25% i get better results =>
![img_20170924_213535](https://user-images.githubusercontent.com/2337234/30805073-2f6b8352-a1f0-11e7-9521-e4ab8d6f9560.jpg)

But my tweaked settings are not optimal yet. I have still some severe curling/warping issues on bridges, and the layer adhesion is far from perfect.

I think Prusa should provide working settings for all of their own filaments. This seems not to be the case for EasyABS.

**Comment by jindrichbenes** [comment]
Hello,

since Prusa does not sell "regular" ABS anymore, but EasyAbys only, Prusa ABS = EasyABS.
The manufacturer does have the 220-240°C range, but we find it better to print this ABS at higher temperatures, 250°C and up.

While there are some cases where fan is beneficial for ABS, fan is turned off in the settings, because most of the times, cooling ABS would be contra-productive.
